---
- name: Update EC2 instances
  hosts: localhost
  connection: local
  tasks:
    - name: Update EC2 state
      amazon.aws.ec2_instance:
          state: "{{ state }}"
          region: us-east-1
          instance_ids:
            "{{instances}}"
        