---
- name: Update LB App
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create EC2 instance
      amazon.aws.elb_application_lb:
        name: demo-blue-green
        region: us-east-1
        security_groups:
          - sg-02ec45a986c61eefe
        subnets:
          - subnet-03bb9bc079113bd96
          - subnet-0216f9716fbf6f60e
        listeners:
          - Protocol: HTTP
            Port: 80
            DefaultActions:
              - Type: forward
                ForwardConfig:
                  TargetGroups:
                    - TargetGroupArn: arn:aws:elasticloadbalancing:us-east-1:268676095163:targetgroup/blue/5dcb5a34055eb87c
                      Weight: "{{ blue }}" #blue
                    - TargetGroupArn: arn:aws:elasticloadbalancing:us-east-1:268676095163:targetgroup/green/f7df989d6f6d518e
                      Weight: "{{ green }}" #green
                  